name: NewRolePlay
main: de.newrp.main
version: ALPHA
description: NewRP Serversystem
author: NewRP Entwicklungs-Team
api-version: 1.16
depend: [ ProtocolLib ]
commands:
  test:
    description: Test command
  sduty:
    description: enter aduty
    aliases: [ aduty ]
  debug:
    description: debug something
  nrp:
    description: write into the chat
  tc:
    description: teamchat
    aliases: [ teamchat, team ]
  heal:
    description: heile einen spieler
  blackjack:
    description: spiele blackjack
  buildmode:
    description: geh in den buildmode
    aliases: [ bm ]
  goto:
    description: teleports you to a point
  weather:
    description: change the weather
    aliases: [ wc, weathercontrol ]
  fly:
    description: let somebody fly
  checkinv:
    description: check a players inv
    aliases: [ getplayerinv, seeinv ]
  tp:
    description: teleport to a player
    aliases: [ teleport, tpto ]
  tphere:
    description: teleport a player to you
    aliases: [ gethere, tph, gth ]
  afk:
    description: set yourself afk
    aliases: [ away ]
  punish:
    description: punish a player
    aliases: [ ban, kick, warn, mute, tempban, tempmute ]
  broadcast:
    description: send a broadcast
    aliases: [ bc ]
  setsupporter:
    description: set a player to supporter
  sudo:
    description: execute a command as another player
  discord:
    description: get the discord link
    aliases: [ dc ]
  forum:
    description: get the forum link
  schreien:
    description: schreie
    aliases: [ shout, s, scream ]
  whisper:
    description: flüstere
    aliases: [ w, wisper ]
  me:
    description: mach etwas
  removewarn:
    description: unwarn a player
    aliases: [ unwarn ]
  unmute:
    description: unmute a player
  kick:
    description: kick a player
  unban:
    description: unban a player
  stats:
    description: get your stats
    aliases: [ statistiken, statistik ]
  checkplayer:
    description: check a player
    aliases: [ check ]
  setmoney:
    description: set a players money
  setlevel:
    description: set a players level
  pay:
    description: pay a player
  daytime:
    description: set a players daytime
    aliases: [ setdaytime ]
  notifications:
    description: set your notifications
    aliases: [ notification ]
  lotto:
    description: play the lotto
  removesupport:
    description: remove a supporter
  demotesupport:
    description: demote a supporter
  banken:
    description: create a bank account
    aliases: [ banks, createkonto, bankkonto ]
  jointeam:
    description: join a team
  addteam:
    description: add a member to your team
  removeteam:
    description: remove a member from your team
  navistop:
    description: stop the route
  navi:
    description: open the navi
  ticket:
    description: create a ticket
    aliases: [ help, report ]
  acceptticket:
    description: accept a ticket
    aliases: [ at ]
  cancelticket:
    description: cancel a ticket
    aliases: [ ct, closeticket ]
  tickets:
    description: view the tickets
  annehmen:
    description: accept something
    aliases: [ accept ]
  setname:
    description: set items name
    aliases: [ setitemname ]
  b:
    description: send a message to the berufschat
    aliases: [ berufschat ]
  invite:
    description: invite a player to your beruf
  uninvite:
    description: uninvite a player from your beruf
  stadtkasse:
    description: view the stadtkasse
  steuern:
    description: view the steuern
    aliases: [ tax, sozialversicherung ]
  joinberuf:
    description: join a beruf
  ablehnen:
    description: decline something
    aliases: [ decline, deny ]
  arbeitslosengeld:
    description: get your arbeitslosengeld
    aliases: [ alg, arbeitsamt ]
  id:
    description: check a player
  wahlen:
    description: vote for somebody
    aliases: [ wahl]
  regierung:
    description: view the regierung
  laufband:
    description: train with laufband
  passwort:
    description: interact with your passwort
    aliases: [password]
  salary:
    description: set the salary
    aliases: [ gehalt]
  abteilung:
    description: set the abteilung
    aliases: [abteilungen, department]
  buy:
    description: buy something
  buyshop:
    description: buy a shop
  shop:
    description: manage your shop
  checkfinances:
    description: check the finances
    aliases: [ finances ]
  checkshop:
    description: check a shop
  ooc:
    description: send a message to the ooc chat
    aliases: [ oocchat, oos, ooschat ]
  bank:
    description: interact with the atm
    aliases: [ atm, geldautomat ]
  registerhouse:
    description: register a house
  rent:
    description: vermiete ein haus
    aliases: [ vermieten ]
  berufskasse:
    description: view the berufskasse
    aliases: [ berufskassen, berufkasse ]
  member:
    description: view the members of your beruf
    aliases: [ members, memberinfo ]
  addberufsdoor:
    description: add a door to a beruf
  installaddon:
    description: install an addon
    aliases: [ insstallhausaddon, installhouseaddon ]
  revive:
    description: revive a player
    aliases: [ rev ]
  friedhof:
    description: view the friedhof
  debugstick:
    description: get a debug stick
    aliases: [ getdebugstick ]
  head:
    description: get a players head
  news:
    description: schalte eine news
  mieter:
    description: check your mieters
    aliases: [ mieters ]
  unrent:
    description: unrent a player
    aliases: [ dismissrent ]
  resetpassword:
    description: reset a players password
    aliases: [ resetpasswort ]
  spectate:
    description: spectate a player
    aliases: [ spec ]
  hauskasse:
    description: view the hauskasse
    aliases: [ housekasse, hkasse ]
  hausaddon:
    description: view the hausaddons
    aliases: [ housesaddons, haddons ]
  addleaderrechte:
    description: add leaderrechte to a player
    aliases: [ giveleaderrechte ]
  removeleaderrechte:
    description: remove leaderrechte from a player
  removeentities:
    description: remove all entities
  flyspeed:
    description: set your flyspeed
  getlocation:
    description: get your location
    aliases: [ location ]
  rnrp:
    description: write into the chat
  duty:
    description: enter duty
    aliases: [ dienstantritt, dienst ]
  msg:
    description: send a message to a player
    aliases: [ message, tell ]
  getgun:
    description: get a gun
  getammo:
    description: get ammo
  checkgun:
    description: check a gun
    aliases: [ guninfo, waffeninfo, winfo, ginfo ]
  achievements:
    description: view your achievements
    aliases: [ achievement, erfolge ]
  setteamleader:
    description: set a player to teamleader
  removeteamleader:
    description: remove a player from teamleader
  forcelotto:
    description: force the lotto
  whitelistip:
    description: whitelist an ip
    aliases: [ ipwhitelist ]
  equip:
    description: equip something
  uncuff:
    description: uncuff a player
    aliases: [ removecuffs ]
  spenden:
    description: spende geld
    aliases: [ spend ]
  staatsmeldung:
    description: send a staatsmeldung
    aliases: [ staatsmeldungen, gov ]
  addhousedoor:
    description: add a door to a house
    aliases: [ housedoor ]
  back:
    description: teleport back
    aliases: [ tpback, goback ]
  baulog:
    description: view the baulog
    aliases: [ baulogs ]
  tragen:
    description: trage jemanden
    aliases: [ carry ]
  removetragensperre:
    description: remove a tragensperre
  sperrinfo:
    description: view the sperrinfo
    aliases: [ sperrinfos ]
  straftat:
    description: add a wantedreason
    aliases: [ straftaten ]
  deletestraftat:
    description: delete a wantedreason
    aliases: [ deletefahndungsgrund ]
  wanted:
    description: view the wanted
    aliases: [ fahndung ]
  removefahndung:
    description: remove a wanted
    aliases: [ deletefahndung ]
  arrest:
    description: arrest a player
    aliases: [ einsperren ]
  unarrest:
    description: unarrest a player
    aliases: [ entlassen ]
  jaillist:
    description: view the jaillist
    aliases: [ jailliste ]
  jailtime:
    description: view the jailtime
    aliases: [ gefangenenzeit ]
  staatschat:
    description: send a message to the staatschat
    aliases: [ govchat, dchat, d ]
  channel:
    description: create a channel
    aliases: [ createchannel ]
  teamspeak:
    description: connect to the teamspeak
    aliases: [ ts ]
  takeshop:
    description: take a shop
  acceptnotruf:
    description: accept a notruf
    aliases: [ acceptcall ]
  donenotruf:
    description: finish a notruf
    aliases: [ finishcall ]
  cancelnotruf:
    description: cancel a notruf
    aliases: [ cancelcall ]
  sharenotruf:
    description: share a notruf
    aliases: [ sharecall ]
  personalausweis:
    description: view your personalausweis
    aliases: [ ausweis, perso ]
  showperso:
    description: show your personalausweis
    aliases: [ showausweis ]
  showfinances:
    description: show your finances
    aliases: [ showfinanzen ]
  showlicenses:
    description: show your licenses
    aliases: [ showlizenzen, licenses ]
  policecomputer:
    description: view the policecomputer
    aliases: [ polizeicomputer, pc ]
  dangerlevel:
    description: set the dangerlevel
    aliases: [ gefahrenstufe ]
  gmx:
    description: shutdown
  signedit:
    description: sign an item
    aliases: [ sign ]
  blockcommand:
    description: block a command
  tipp:
    description: view the tippoftheday
    aliases: [ totd, tippoftheday ]
  zeitung:
    description: publish a zeitung
  aab:
    description: secret
  requeuenotruf:
    description: requeue a notruf
    aliases: [ requeuecall ]
  ramm:
    description: ramm a door
  transferticket:
    description: transfer a ticket
  health:
    description: view your health
  notrufe:
    description: view the notrufe
    aliases: [ calls ]
  dropgun:
    description: drop a gun
    aliases: [ dropwaffe, dropwaffen, dropguns ]
  rezept:
    description: stelle ein rezept aus
    aliases: [ rezepte ]
  selfstorage:
    description: open the selfstorage
  checkselfstorage:
    description: check the selfstorage
  removeselfstorage:
    description: remove the selfstorage
  removecheckpoints:
    description: remove all checkpoints
  vertrag:
    description: create a vertrag
  vertraglist:
    description: view the vertraege
    aliases: [ contracts, verträge ]
  erstattung:
    description: erstattung
  showvertrag:
    description: show a vertrag
  reinforcement:
    description: call reinforcement
    aliases: [ backup, reinf, verstärkung ]
  premium:
    description: check your premium
  call:
    description: call a player
    aliases: [ anrufen ]
  pickup:
    description: pickup a call
    aliases: [ p ]
  hangup:
    description: hangup a call
    aliases: [ h ]
  registerplayer:
    description: register a player
  getshulker:
    description: get a shulker
  sms:
    description: send a sms
    aliases: [ messenger ]
  breakingnews:
    description: send a breakingnews
  akku:
    description: view your akku
    aliases: [ aufladen ]
  removestadtkasse:
    description: remove from stadtkasse
  houseban:
    description: ban a player from a house
    aliases: [ hv, hausverbot ]
  aktien:
    description: view your aktien
    aliases: [ aktie, aktienmarkt ]